"""Deterministic correction section for a regeneration attempt.

Pure function of (previous evaluation record, spec, attempt number, failure history).
Uses only: failing reason codes, the evaluator's observations of the PREVIOUS generated
image (always framed as such), and the spec's own values. It never receives the reference
profile, its descriptions, or critical flags; the reference image remains the source of truth.
"""

from dataclasses import dataclass, field

from adgen import config
from adgen.spec import GenerationSpec

OBSERVED = "Observed in the previous generated image:"
HEADER = (
    "CORRECTIONS FROM PREVIOUS ATTEMPT (attempt {attempt} of {max_attempts})\n"
    "The previous generated image was rejected by automated quality checks. Keep everything that "
    "was already correct and fix only the issues below. The attached reference image remains the "
    "source of truth for the product."
)
# Composite mode: the scene request carries no image, so the header must not mention an attachment.
COMPOSITE_HEADER = (
    "CORRECTIONS FROM PREVIOUS ATTEMPT (attempt {attempt} of {max_attempts})\n"
    "The previous generated image was rejected by automated quality checks. Keep everything that "
    "was already correct and fix only the issues below. The approved product reference remains the "
    "source of truth for the task."
)
MAX_QUOTES_PER_LINE = 3

SPECIFIC_PRODUCT_CODES = (
    "PRODUCT_MARK_ALTERED", "PRODUCT_MARK_MISSING", "PRODUCT_BRANDING_DISTORTED", "PRODUCT_BRANDING_ADDED",
    "PRODUCT_COLOR_MATERIAL_ALTERED", "PRODUCT_SHAPE_ALTERED", "PRODUCT_DETAIL_ALTERED",
)
SEASON_RATING_CODES = ("CONTEXT_SEASON_WEAK", "CONTEXT_SEASON_ABSENT", "CONTEXT_SEASON_CONTRADICTORY")


@dataclass(frozen=True)
class Correction:
    text: str                      # full section appended to the base prompt
    body: str                      # correction lines only (used for identical-request detection)
    lines: list = field(default_factory=list)       # [{"section", "codes", "text"}]
    suppressed: list = field(default_factory=list)  # codes folded into more specific lines
    persisting: dict = field(default_factory=dict)  # code -> first attempt of its unbroken streak
    excluded: list = field(default_factory=list)    # failing codes not sent (section not generated by model)


def _clean(text: str) -> str:
    text = " ".join(str(text).split()).replace('"', "'")
    limit = config.MAX_EVIDENCE_CHARS
    return text if len(text) <= limit else text[: limit - 1].rstrip() + "…"


def _quotes(items) -> str:
    unique = []
    for item in items:
        cleaned = _clean(item)
        if cleaned and cleaned not in unique:
            unique.append(cleaned)
    return "; ".join(f'"{q}"' for q in unique[:MAX_QUOTES_PER_LINE])


def _observed(items) -> str:
    quotes = _quotes(items)
    return f" {OBSERVED} {quotes}." if quotes else ""


def failing_reasons(evaluation: dict) -> list[dict]:
    """Failing reasons in gate order (text, product, context); recorded-only items excluded."""
    reasons = []
    for section in ("text", "product", "context"):
        for reason in evaluation["checks"].get(section, {}).get("reasons", []):
            reasons.append({**reason, "section": section})
    return reasons


def _persistence(history: list[list[str]]) -> dict:
    """For codes in the latest attempt, the first attempt of their unbroken streak (only if > 1 long)."""
    if not history:
        return {}
    latest = len(history)
    result = {}
    for code in history[-1]:
        start = latest
        while start > 1 and code in history[start - 2]:
            start -= 1
        if start < latest:
            result[code] = start
    return result


def _text_lines(reasons, spec):
    lines = []
    required = spec.required_text
    for r in reasons:
        code = r["code"]
        if code == "TEXT_MISMATCH":
            msg = (f"The advertising text was not exact.{_observed([r.get('found', '')])} Render exactly "
                   f'"{required}", character for character, with identical spelling, capitalization and punctuation.')
        elif code == "TEXT_MISSING":
            msg = f'The required text was missing. Render exactly "{required}" once, clearly legible.'
        elif code == "TEXT_DUPLICATED":
            msg = f'The required text appeared {r.get("occurrences", "more than one")} times. Render "{required}" exactly once.'
        elif code == "TEXT_EXTRA_AD_COPY":
            msg = (f"Extra advertising text appeared.{_observed([r.get('extra', '')])} Remove it; the only "
                   f'advertising text must be "{required}".')
        else:
            continue
        lines.append({"section": "TEXT", "codes": [code], "text": msg})
    return lines


def _product_lines(reasons):
    by_code: dict = {}
    for r in reasons:
        by_code.setdefault(r["code"], []).append(r)

    def evidence(code):
        items = []
        for r in by_code[code]:
            ev = r.get("evidence", "")
            observed_text = r.get("observed_text", "")
            if code == "PRODUCT_BRANDING_DISTORTED" and observed_text and observed_text not in ev:
                ev = f"{ev} (read as '{observed_text}')" if ev else f"branding read as '{observed_text}'"
            if code == "PRODUCT_BRANDING_ADDED" and r.get("location"):
                ev = f"{ev} ({r['location']})"
            items.append(ev)
        return items

    templates = [
        ("PRODUCT_REPLACED", "A different product was shown.{obs} Show exactly the product in the reference image."),
        ("PRODUCT_MARK_ALTERED", "A distinctive mark on the product was changed.{obs} Reproduce every mark, emblem "
         "and logo exactly as in the reference image: same shape, geometry, proportions, color and position. Do not "
         "substitute a different or more conventional symbol."),
        ("PRODUCT_MARK_MISSING", "A distinctive mark from the reference image was missing.{obs} Include every mark, "
         "emblem and logo exactly as in the reference image."),
        ("PRODUCT_BRANDING_DISTORTED", "Branding text on the product was distorted.{obs} Reproduce all branding "
         "exactly as printed in the reference image, sharp and legible."),
        ("PRODUCT_BRANDING_ADDED", "A logo or mark that is not in the reference image appeared.{obs} Remove it; add "
         "no marks that are not in the reference image."),
        ("PRODUCT_COLOR_MATERIAL_ALTERED", "A product color or material differed from the reference.{obs} Match the "
         "reference image's colors and materials exactly."),
        ("PRODUCT_SHAPE_ALTERED", "The product's shape or proportions differed from the reference.{obs} Match the "
         "reference image's shape exactly."),
        ("PRODUCT_DETAIL_ALTERED", "A product detail differed from the reference.{obs} Match every detail of the "
         "reference image."),
    ]
    lines, suppressed = [], []
    for code, template in templates:
        if code in by_code:
            lines.append({"section": "PRODUCT", "codes": [code],
                          "text": template.format(obs=_observed(evidence(code)))})

    # Generic design deviation adds nothing when a specific product line already exists.
    if "PRODUCT_DESIGN_DEVIATION" in by_code:
        if any(c in by_code for c in SPECIFIC_PRODUCT_CODES) or "PRODUCT_REPLACED" in by_code:
            suppressed.append("PRODUCT_DESIGN_DEVIATION")
        else:
            lines.append({"section": "PRODUCT", "codes": ["PRODUCT_DESIGN_DEVIATION"],
                          "text": f"The product's design differed from the reference."
                                  f"{_observed(evidence('PRODUCT_DESIGN_DEVIATION'))} Show the exact same product "
                                  "design as the reference image."})
    if "PRODUCT_INSUFFICIENT_EVIDENCE" in by_code:
        lines.append({"section": "PRODUCT", "codes": ["PRODUCT_INSUFFICIENT_EVIDENCE"],
                      "text": "The product's distinctive features were not visible. Show the product clearly, from "
                              "an angle where its distinctive features are visible."})
    return lines, suppressed


def _context_lines(reasons, spec):
    geo, season = spec.geography, spec.season
    lines, suppressed = [], []
    codes = [r["code"] for r in reasons]

    for r in reasons:
        if r["code"] in ("CONTEXT_GEO_WEAK", "CONTEXT_GEO_ABSENT"):
            obs = _observed(r.get("cues", [])) or f" {OBSERVED} no location-specific cues."
            lines.append({"section": "CONTEXT", "codes": [r["code"]],
                          "text": f"The setting did not clearly read as {geo}.{obs} Establish {geo} through several "
                                  "location-specific visual cues (for example architecture, street layout, signage "
                                  "script, local details), not a generic scene."})
        elif r["code"] == "CONTEXT_GEO_CONTRADICTORY":
            lines.append({"section": "CONTEXT", "codes": [r["code"]],
                          "text": f"The scene contained cues of a different location."
                                  f"{_observed(r.get('contradicting_cues', []))} Remove them; the setting must "
                                  f"clearly be {geo}."})

    # One consolidated seasonal line for rating + conflict codes.
    conflicts = [r for r in reasons if r["code"] == "CONTEXT_SEASON_CONFLICT"]
    rating = [c for c in codes if c in SEASON_RATING_CODES]
    if conflicts:
        obs = _observed([f"{r.get('cue', '')} ({r.get('reason', '')})" if r.get("reason") else r.get("cue", "")
                         for r in conflicts])
        text = f"Elements of another season appeared.{obs} Remove them; every seasonal element must fit {season}"
        text += f", and {season} must read clearly throughout." if rating else "."
        lines.append({"section": "CONTEXT", "codes": rating + ["CONTEXT_SEASON_CONFLICT"], "text": text})
        suppressed.extend(rating)
    elif rating:
        lines.append({"section": "CONTEXT", "codes": rating,
                      "text": f"The season did not read clearly as {season}. Strengthen {season} cues and remove "
                              f"anything that contradicts {season}."})
    return lines, suppressed


ALL_SECTIONS = ("TEXT", "PRODUCT", "CONTEXT")


def build_correction(
    evaluation: dict, spec: GenerationSpec, attempt: int, max_attempts: int, history: list[list[str]],
    sections: tuple = ALL_SECTIONS,
) -> Correction:
    """Correction section for `attempt`, from the previous attempt's evaluation record.

    `history` lists the failing reason codes of attempts 1..attempt-1 (the last entry
    belongs to `evaluation`) and is used only to mark still-unresolved issues.
    `sections` limits which corrections are sent (composite mode: TEXT and CONTEXT only,
    because the scene model never draws the product); excluded codes are reported.
    """
    reasons = failing_reasons(evaluation)
    text_lines = _text_lines([r for r in reasons if r["section"] == "text"], spec)
    product_lines, sup_p = _product_lines([r for r in reasons if r["section"] == "product"])
    context_lines, sup_c = _context_lines([r for r in reasons if r["section"] == "context"], spec)
    excluded = [r["code"] for r in reasons if r["section"].upper() not in sections]
    lines = [line for line in text_lines + product_lines + context_lines if line["section"] in sections]
    sup_p = sup_p if "PRODUCT" in sections else []
    sup_c = sup_c if "CONTEXT" in sections else []
    persisting = _persistence(history)

    rendered = []
    for line in lines:
        starts = [persisting[c] for c in line["codes"] if c in persisting]
        prefix = f"STILL UNRESOLVED since attempt {min(starts)}: " if starts else ""
        rendered.append(f"- [{line['section']}] {prefix}{line['text']}")
    body = "\n".join(rendered)
    header = HEADER if "PRODUCT" in sections else COMPOSITE_HEADER  # no PRODUCT section = composite mode
    text = header.format(attempt=attempt, max_attempts=max_attempts) + ("\n" + body if body else "")
    return Correction(text=text, body=body, lines=lines, suppressed=sup_p + sup_c, persisting=persisting,
                      excluded=excluded)
