"""Reference profiles: model-drafted, human-approved, evaluator-only.

Workflow: reference image -> draft (1 model call) -> human review ->
approved profile with "human_verified": true -> used by the evaluator.
Drafts (*.draft.json) are never used for evaluation. The generator never
reads profiles.
"""

import json
import os
import re
from datetime import datetime, timezone
from pathlib import Path

from adgen import config
from adgen.evaluator import EvaluationError
from adgen.evaluator import judge
from adgen.evaluator.schemas import validate_profile, validate_profile_draft_output
from adgen.image_io import load_reference_image

DRAFT_SUFFIX = ".draft.json"
NAME_PATTERN = re.compile(r"^[A-Za-z0-9_-]+$")

# Proposed defaults only; the human reviewer decides the final critical flags.
DEFAULT_CRITICAL_BY_KIND = {"shape": True, "color_material": True, "mark": True, "detail": False}
DEFAULT_BRANDING_CRITICAL = True


def load_approved_profile(reference_sha256: str, profiles_dir: Path = config.PROFILES_DIR) -> tuple[dict, Path]:
    """Find the approved profile for a reference image. Raises EvaluationError otherwise."""
    matches = []
    for path in sorted(Path(profiles_dir).glob("*.json")):
        if path.name.endswith(DRAFT_SUFFIX):
            continue
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as e:
            raise EvaluationError("EVAL_INVALID_PROFILE", f"Cannot read profile {path.name}: {e}") from None
        if isinstance(data, dict) and data.get("reference_image_sha256") == reference_sha256:
            matches.append((path, data))

    if not matches:
        raise EvaluationError(
            "EVAL_NO_APPROVED_PROFILE",
            f"No approved profile for reference image sha256={reference_sha256[:12]}... in {profiles_dir}. "
            "Create a draft, review it, and save it with human_verified=true.",
        )
    if len(matches) > 1:
        names = [p.name for p, _ in matches]
        raise EvaluationError("EVAL_INVALID_PROFILE", f"Several profiles match this reference image: {names}")

    path, data = matches[0]
    validate_profile(data)
    if data["human_verified"] is not True:
        raise EvaluationError(
            "EVAL_NO_APPROVED_PROFILE", f"Profile {path.name} is not human_verified; it cannot be used."
        )
    return data, path


def _slug(text: str) -> str:
    return re.sub(r"[^a-z0-9]+", "_", text.lower()).strip("_") or "item"


def _unique(slug: str, used: set) -> str:
    candidate, n = slug, 2
    while candidate in used:
        candidate, n = f"{slug}_{n}", n + 1
    used.add(candidate)
    return candidate


def build_draft_profile(model_output: dict, reference_image: str, sha256: str, raw_text: str) -> dict:
    """Wrap validated model output as an UNVERIFIED profile draft."""
    used: set = set()
    notes = [
        "DRAFT generated by a model. Not trusted until a human reviews it.",
        "Check every description against the reference image, especially mark geometry and branding text.",
        "critical flags were proposed by a fixed rule (mark/shape/color_material: true, detail: false, "
        "branding: true). Adjust each one.",
        "When approved: save as profiles/<name>.json with human_verified=true, verified_by and verified_at.",
    ]
    attributes = [
        {
            "id": _unique(_slug(a["id"]), used),
            "kind": a["kind"],
            "critical": DEFAULT_CRITICAL_BY_KIND[a["kind"]],
            "description": a["description"],
        }
        for a in model_output["attributes"]
    ]
    branding = []
    for b in model_output["branding"]:
        if not b["text"].strip():
            notes.append(f"Dropped branding entry {b['id']!r} with empty text.")
            continue
        branding.append({
            "id": _unique(_slug(b["id"]), used),
            "text": b["text"],
            "location": b["location"],
            "critical": DEFAULT_BRANDING_CRITICAL,
        })

    return {
        "profile_version": 1,
        "reference_image": reference_image,
        "reference_image_sha256": sha256,
        "human_verified": False,
        "verified_by": "",
        "verified_at": "",
        "review_notes": notes,
        "draft_source": {
            "model": config.EVALUATOR_MODEL,
            "created_at": datetime.now(timezone.utc).isoformat(timespec="seconds").replace("+00:00", "Z"),
            "raw_model_output": raw_text,
        },
        "product_category": model_output["product_category"],
        "attributes": attributes,
        "branding": branding,
    }


def _display_path(path: Path) -> str:
    path = Path(path).resolve()
    try:
        return path.relative_to(config.PROJECT_ROOT).as_posix()
    except ValueError:
        return str(path)


def create_profile_draft(
    image_path: Path, client, name: str, profiles_dir: Path = config.PROFILES_DIR, secret: str | None = None
) -> Path:
    """Make the one-time draft call for a reference image and save profiles/<name>.draft.json."""
    if not NAME_PATTERN.match(name):
        raise EvaluationError("EVAL_INVALID_PROFILE", "Profile name may only contain letters, digits, '-' and '_'.")
    draft_path = Path(profiles_dir) / f"{name}{DRAFT_SUFFIX}"
    if draft_path.exists():
        raise EvaluationError("EVAL_DRAFT_EXISTS", f"{draft_path} already exists; not overwriting.")

    reference = load_reference_image(image_path)
    raw_text = judge.call_model(client, judge.build_profile_draft_request(reference), secret)
    model_output = validate_profile_draft_output(judge.parse_json(raw_text))
    draft = build_draft_profile(model_output, _display_path(image_path), reference.sha256, raw_text)
    validate_profile(draft)  # structurally valid, but human_verified is False

    draft_path.parent.mkdir(parents=True, exist_ok=True)
    tmp = draft_path.with_name(draft_path.name + ".tmp")
    tmp.write_text(json.dumps(draft, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    os.replace(tmp, draft_path)
    return draft_path
